### ISSUE TITLE
Compatibility of test net?

### ISSUE THREAD

**Issue by fkramer90** [kopanitsa/web3-arduino#2]
Is it only compatible with the main network or can I also work with rinkeby? i have already read that it is difficult to access rinkeby with the standard web3 package.

**Comment by kopanitsa** [comment]
Sorry for late. Yes, you can use for Rinkeby. Please refer below
https://github.com/kopanitsa/web3-arduino/blob/master/example/basic_web3/basic_web3.ino

If you use set url like below, app will be connected to Rinkeby chain.
```
#define INFURA_HOST "rinkeby.infura.io"
#define INFURA_PATH "/<YOUR_INFURA_ID>"
```
