### ISSUE TITLE
forbidden access to infura

### ISSUE THREAD

**Issue by toutou8148** [kopanitsa/web3-arduino#20]
Hi,

I am trying to get access to infura, however I get the following error:

Starting connection to server...
Connected to server!
HTTP/1.1 403 Forbidden
Date: Tue, 15 Dec 2020 13:48:18 GMT
Content-Type: application/json
Content-Length: 163
Connection: close
Vary: Origin
{"jsonrpc":"2.0","id":0,"error":{"code":-32600,"message":"project ID is required","data":{"reason":"project ID not provided","see":"https://infura.io/dashboard"}}}

This is my code:

#include <WiFi.h>
#include <Web3.h>

#define ENV_SSID     "**************"
#define ENV_WIFI_KEY "***********"

string* INFURA_HOST = new string("mainnet.infura.io");
string* INFURA_PATH = new string("/PROECT_ID");
Web3 web3(INFURA_HOST, INFURA_PATH);

void web3_example();

void setup() {
    Serial.begin(115200);
    for(uint8_t t = 4; t > 0; t--) {
        Serial.printf("[SETUP] WAIT %d...\n", t);
        Serial.flush();
        delay(1000);
    }

    WiFi.begin(ENV_SSID, ENV_WIFI_KEY);

    // attempt to connect to Wifi network:
    while (WiFi.status() != WL_CONNECTED) {
        Serial.print(".");
        // wait 1 second for re-trying
        delay(1000);
    }

    Serial.println("Connected to WiFi");

    net_example();
}
void loop() {
    // put your main code here, to run repeatedly:
}

void web3_example() {
    string result = web3.Web3ClientVersion();
    Serial.println("web3_ClientVersion");
    Serial.println(result.c_str());
}

**Comment by toutou8148** [comment]
I have fixed the error by making this modification:

string* INFURA_PATH = new string("/**v3**/PROJECT_ID");

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @toutou8148)
